project_id = "fkimfnqpdfwlkacrenzu"

[functions.generate-course]
verify_jwt = false

[functions.generate-certificate]
verify_jwt = false

[functions.evaluate-answers]
verify_jwt = false

[functions.generate-pdf-certificate]
verify_jwt = false

[functions.send-certificate-email]
verify_jwt = false
